name: cloudpayments
description: A Flutter plugin for integrating Cloudpaymanets in Android and iOS applications.
version: 0.3.0
repository: https://github.com/shushper/cloudpayments

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.shushper.cloudpayments
        pluginClass: CloudpaymentsPlugin
      ios:
        pluginClass: CloudpaymentsPlugin

